build:
  environment:
    php: '5.5.25'
  dependencies:
    before:
      - composer install
  tests:
    override:
      -
        idle_timeout: 600
        command: './vendor/bin/phpunit --coverage-clover=.coverage.xml'
        coverage:
            file: '.coverage.xml'
            format: 'clover'
filter:
  excluded_paths:
    - "database/"
    - "config/"
    - "tests/"
